name: CICD

on:
  push:
    branches:
    - master
    - staging
    - develop
  pull_request:
    branches:
    - master
    - staging
    - develop

jobs:
  # The "Build" workflow
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.0'
      
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      
      - name: Run build
        run: go build .
      
      - name: Run vet & lint
        run: |
          go vet .
          golint .

      - name: Run testing
        run: go test -v

      #- name: Run GoReleaser
      #  uses: goreleaser/goreleaser-action@master
      #  with:
      #    version: latest
      #    args: release --rm-dist
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN}}

      #- name: Deploy to Docker registry
      #  uses: docker/build-push-actions@v1
      #  with:
      #    username: ${{ secrets.DOCKER_USERNAME}}
      #    password: ${{ secrets.DOCKER_PASSWORD}}
      #    repository: tobiasgrott/gosimple
      #    tag_with_ref: true
